# Generated by Django 4.2.3 on 2023-07-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
        migrations.AddField(
            model_name='event',
            name='client_id',
            field=models.CharField(default='1', max_length=50),
            preserve_default=False,
        ),
    ]
