# Generated by Django 4.2.3 on 2023-07-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_event_client_event_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='session_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
